#!/bin/bash
# Pure function library -- write_db_env() projects the DATABASE half of
# backend/.env into backend/.env.db. Sourced by install_velo.sh (fresh
# install) and velo-manage.sh (update), so the two never carry separate
# copies of the key list.
#
# WHY THIS FILE EXISTS (T-32 item 9): docker-compose.yml used to feed
# postgres and redis the WHOLE backend/.env, so `docker compose exec
# postgres env` printed the Stripe keys, the bot token, SECRET_KEY and
# COMMS_SERVICE_TOKEN. Compromising either datastore meant handing over
# every application secret on the box. Both services now read this
# narrow projection instead; backend/.env stays the single source of the
# passwords and .env.db is derived, never hand-edited.
#
# ⚠ RECONSTRUCTED 2026-08-12, NOT the original. The T-32 commit
# (98faa41a) shipped the two call sites and the compose change but never
# committed this library -- `git log --all -- scripts/env-render.sh` is
# empty and nothing ignores the path, so it existed only on its author's
# disk. A `velo update` onto a box without a pre-existing .env.db then
# failed at the first compose command ("env file .../backend/.env.db not
# found"), which is exactly how this was found. The contract below is
# recovered from the two call sites -- install_velo.sh (`write_db_env
# <src> <dst>`, aborts on non-zero) and velo-manage.sh (same, plus a
# `[ -f ]` guard that silently skips when this file is absent) -- and
# from docker-compose.yml's own comments naming what each container
# consumes. If the author's version lands later, THEIRS WINS: this is a
# stand-in for a missing file, not a competing design.

# The complete allowlist, and the only thing that decides what leaves
# backend/.env. postgres:16 reads the three POSTGRES_* keys at init;
# redis reads REDIS_PASSWORD, both for `--requirepass` and for the
# healthcheck's REDISCLI_AUTH. Anything not named here is, by design,
# invisible to both containers -- which is the entire point of the file,
# so extend this list only with a reason.
_DB_ENV_KEYS=(
    POSTGRES_DB
    POSTGRES_USER
    POSTGRES_PASSWORD
    REDIS_PASSWORD
)

# write_db_env <src backend/.env> <dst backend/.env.db>
#
# Copies the allowlisted lines VERBATIM -- no parse, no requote. A
# password may legitimately contain '#', '=', spaces or quotes, and
# compose's env_file reader takes the raw KEY=value line; re-emitting a
# shell-quoted value would change what the container receives. Lines are
# matched on an exact `KEY=` prefix, so POSTGRES_PASSWORD_FILE or a
# commented-out `#POSTGRES_DB=` is not mistaken for the real key.
#
# Returns 0 on success. Non-zero (with the partial file removed) when the
# source is unreadable or any key is missing -- both callers treat that
# as fatal, and rightly: postgres initialising with no POSTGRES_PASSWORD
# is worse than a stopped deploy.
write_db_env() {
    local src="$1" dst="$2"

    if [ -z "$src" ] || [ -z "$dst" ]; then
        echo "write_db_env: usage: write_db_env <src .env> <dst .env.db>" >&2
        return 2
    fi

    if [ ! -r "$src" ]; then
        echo "write_db_env: cannot read $src" >&2
        return 1
    fi

    local tmp="${dst}.tmp.$$"

    # umask BEFORE the first write, not chmod after: the file holds the
    # database passwords, and a create-then-chmod leaves a window where
    # it is world-readable.
    local old_umask
    old_umask=$(umask)
    umask 077

    {
        echo "# GENERATED by scripts/env-render.sh -- DO NOT EDIT."
        echo "# Narrow db env (T-32 item 9): the only keys postgres and redis"
        echo "# consume, projected out of backend/.env. Edit backend/.env and"
        echo "# re-run \`velo update\` (or the installer) to regenerate."
    } > "$tmp" || {
        umask "$old_umask"
        rm -f "$tmp"
        echo "write_db_env: cannot write $tmp" >&2
        return 1
    }

    # Belt AND braces, because the umask alone was measured NOT to be
    # enough: where `mv` below degrades from a rename into a copy, the
    # destination is created under the CALLER's umask and the 077 set
    # here is lost -- observed producing a world-readable 0644 .env.db.
    # An explicit mode on both the temp file and the final one is the
    # only form that does not depend on which mv you got.
    chmod 600 "$tmp" 2>/dev/null || true

    local key missing=()
    for key in "${_DB_ENV_KEYS[@]}"; do
        # Last occurrence wins, matching how compose reads a repeated key.
        local line
        line=$(grep -E "^${key}=" "$src" | tail -n 1)
        if [ -z "$line" ]; then
            missing+=("$key")
            continue
        fi
        printf '%s\n' "$line" >> "$tmp"
    done

    umask "$old_umask"

    if [ ${#missing[@]} -gt 0 ]; then
        rm -f "$tmp"
        echo "write_db_env: $src is missing required key(s): ${missing[*]}" >&2
        echo "write_db_env: refusing to write a partial $dst -- postgres or" >&2
        echo "write_db_env: redis would start without credentials." >&2
        return 1
    fi

    # Atomic swap: a reader (a concurrent compose) sees either the old
    # file or the new one, never a half-written one.
    if ! mv -f "$tmp" "$dst"; then
        rm -f "$tmp"
        echo "write_db_env: cannot move $tmp -> $dst" >&2
        return 1
    fi

    # See the chmod above: this is the one that actually holds when mv
    # copied rather than renamed.
    chmod 600 "$dst" 2>/dev/null || true

    return 0
}
